footerPath: 'src/partials/footer.hbs'
headerPath: 'src/partials/head.hbs'

destination: '/public/patterns'

compiler: 'handlebars'

plugins:
  stylizer.handlebars:
  stylizer.getPatterns:
  stylizer.patternData:
  stylizer.drupalExport:
  sassColors/sassColors:
    settings:
      file: './_colors.scss'
